92 user's NFT collection
amosproj/amos2021ws07-nft-development pull request #141
Opened 2021-12-13 19:30 UTC by steinkohl

Not pretty at all.
But the core layout should match mostly.
login in -> http://localhost:3000/user/myCollection

2021-12-15 05:02 UTC, dominic-heil requested changes
Decent start :D I added a few things to take a look at.

2021-12-15 05:02 UTC, dominic-heil commented on frontend/src/pages/NFTCollection.js
> +					<img src={ ExampleUserPic } alt="User Pic"/>
If you want to make the image look more like in the mockups, add a wrapper ´div´ arround the image, resize the div with the style attributes, give the div a `backgroundColor` and add a `borderRadius` to the div to make it a circle.

2021-12-15 05:02 UTC, dominic-heil commented on frontend/src/pages/NFTCollection.js
> +			<HeaderTypography style={{ fontSize: "36px", fontWeight: "bold" }}>Your NFT Collection</HeaderTypography>
In the mockup the font size is 22px.

2021-12-15 19:47 UTC, steinkohl commented
Thanks a lot for your feedback!
I will try to implement the changes until meeting.

2021-12-16 10:36 UTC, tuilagio commented on frontend/src/pages/NFTCollection.js
> +// import { activeTextColor, secondaryTextColor, textColor } from "../assets/jss/colorPalette";
remove commented out code when you are done :)

2021-12-16 10:38 UTC, tuilagio commented on frontend/src/pages/NFTCollection.js
> +				<Grid direction="row">
not related, but I though nested Grid is possible?
https://mui.com/components/grid/#nested-grid

2021-12-17 03:45 UTC, dominic-heil commented on frontend/src/pages/NFTCollection.js
> +				<Grid direction="row">
Ah, didn't know that. Then probably make them a `<Grid container item direction="row">...`

2022-01-11 10:37 UTC, dominic-heil commented
Just updated the design to look more like the mockups. Should be mergable now

2022-01-11 10:37 UTC, dominic-heil approved these changes

2022-01-12 10:50 UTC, tuilagio commented
I would say we should merge this quickly and move to other important features. Besides, looks perfect to me!

2022-01-12 10:50 UTC, tuilagio approved these changes

2022-01-12 10:50 UTC, merged