init api
amosproj/amos2021ws07-nft-development pull request #17
Opened 2021-11-03 22:09 UTC by tuilagio

This is a very simple draw of API endpoints for our backend.
This include endpoints for user, wallet, NFT.

2021-11-03 22:54 UTC, krisutofu commented
Great work, Que!
How can I set it up so that I can test it properly?

2021-11-03 22:58 UTC, krisutofu requested changes
There are nevertheless some quality aspects that I think should be improved.
At some parts, the description is empty.
At some parts, I miss certain considerations. I think, we should do this story thoroughly because future work will be based on this.

2021-11-03 23:02 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +      description: "Return a long list of items belonging to a queried category"
This is cool but do we really feature NFT categories? At the moment we only offer only map region NFTs, or is it difficult to add later? Is Nürnburg and Riga supposed to be two different categories?

2021-11-03 23:04 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +          description: "Invalid ID supplied"
What is the difference between invalid category identifier and not found? If there are invalid IDs, how is the defined naming pattern?

2021-11-03 23:05 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +          description: "Pet not found"
What means "pet not found"?

2021-11-03 23:06 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +          description: "Pet not found"
can you also set Wallet information?

2021-11-03 23:07 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +      - "application/json"
What is an "NFT record" or why does it return a JSON?

2021-11-03 23:17 UTC, krisutofu commented
I think, the terminology used here should be defined in the product glossary:
https://docs.google.com/spreadsheets/d/1bU3gAi5QRDXG22NluQ3n4g-0UkEDGOdO0oJZqlJ85UQ/edit#gid=12

They are not necessarily clear to me like "asset category" or "NFT record".

2021-11-03 23:19 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +        description: "ID of NFT record to return"
copy-paste error

2021-11-03 23:23 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +      description: "Returns a List of NFT records"
Who is authorized to request that list?

2021-11-03 23:24 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +      description: "Returns a single wallet's information"
Who is authorized to obtain this information?

2021-11-03 23:24 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +          description: "Pet not found"
What about "access denied" error?

2021-11-03 23:24 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +          description: "Username not found"
"Access denied" error?

2021-11-03 23:26 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +      summary: "Returns NFT inventories by status"
Sounds like an operation that uses "status" as input but parameters are empty.

2021-11-03 23:26 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +      description: ""
misses description

2021-11-03 23:27 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +      description: ""
who is allowed to place an order?

2021-11-03 23:27 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +        description: "order placed for purchasing the pet"
which "pet"?

2021-11-03 23:28 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +        description: "ID of pet that needs to be fetched"
-> "pet"

2021-11-03 23:30 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +      description: "For valid response try integer IDs with value >= 1 and <= 10. Other values will generate exceptions."
who is allowed to do get this purchase order?

2021-11-03 23:31 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +      summary: "Delete purchase order by ID"
who is allowed to delete the purchase order?

2021-11-03 23:32 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +      description: "This can only be done by the logged in user."
How can a user without account create an account if only logged in users can create accounts?

2021-11-03 23:34 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +          description: "successful operation"
what about duplicate user creations ? Are there other any other invalid user creations?

2021-11-03 23:35 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +      summary: "[Test only] Creates list of users with given input list"
why do we need a separate endpoint for List and array of user accounts?

2021-11-03 23:36 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +      description: "ONLY FOR TEST"
This could also be useful for admins but it's dangerous for non-admins to create just many accounts and could allow for fraud.

2021-11-03 23:37 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +          description: "successful operation"
some response conditions as for single-user creation

2021-11-03 23:37 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +      description: ""
Description missing

2021-11-03 23:38 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +        description: "The password for login in clear text"
I really hope the server will not receive any plain text password. Is this supposed to define client side input?

2021-11-03 23:39 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +              description: "calls per hour allowed by the user"
what are "calls per hour"?

2021-11-03 23:40 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +      description: ""
description missing

2021-11-03 23:40 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +      description: ""
this should only work for logged in users or admins.

2021-11-03 23:40 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +      description: "This can only be done by the logged in user."
can we create admin accounts?

2021-11-03 23:42 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +          description: "successful operation"
or unsuccessful in case of a stale or even invalid session.

2021-11-03 23:42 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +      description: ""
description missing

2021-11-03 23:43 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +      description: ""
also we need to differentiate between private user info and public user info.

2021-11-03 23:45 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +          description: "User not found"
a good response should be possible.
Also, "access denied"

2021-11-03 23:45 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +      description: "This can only be done by the logged in user."
Or maybe the admin.

2021-11-03 23:46 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +        "400":
"200" is missing.
What happens, if the admin deletes a user account twice?

2021-11-03 23:47 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +      description: ""
description is missing

2021-11-03 23:48 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +        format: "string"
what is the "string" format?

2021-11-03 23:50 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +        "200":
what about file too large? Are user profiles controlled for appropriate content?

2021-11-03 23:51 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +      write:pets: "modify pets in your account"
The "pet" example could be changed to NFT, but this is not dramatic.

2021-11-03 23:52 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +  PlaceHolder:
What for is "Placeholder" used?

2021-11-03 23:53 UTC, krisutofu commented on Documentation/API/nft_the_world.yml
> +  Order:
This format needs to be adjusted to our project. This is probably from the original template.

2021-11-04 10:29 UTC, Floinko commented
Good place to put the documentation. I will add the other documents later. Also there are some good points here.
However i think this needs some more work. According to the backend-techstack document, the user management will be handled by appwrite and is obsolete here. Also the ordering process will be processed by the ethereum blockchain. 
=> converted to draft.

2021-11-04 10:29 UTC, closed without merging