184 reserved nfts logic
amosproj/amos2021ws07-nft-development pull request #198
Opened 2022-01-23 23:16 UTC by BerinikeTech

2022-01-25 07:45 UTC, JaPilgrim requested changes
Requested Changes, Rest looks good & is working

2022-01-25 07:45 UTC, JaPilgrim commented on blockchain/contracts/MainContract.sol
>              "Cannot join the drop anymore."
As now "availableNFTs" gets diminished (call to remove() ) within the function it doesnt represent the number of total NFTs available anymore, but the number of currently available NFTs. This throws error if at excactly 50% reserved NFTs of drop. Either:
- work with numberofURIs
- dont remove from availableNFTs at all

2022-01-25 19:33 UTC, dominic-heil approved these changes
LGTM

2022-01-25 19:43 UTC, steinkohl approved these changes
Tested in remix - LGTM

2022-01-26 09:55 UTC, JaPilgrim requested changes
While Testing and executing "Buy" I get just an error message "Fail" 
![image](https://user-images.githubusercontent.com/92588281/151141759-8fd21209-e9d8-4285-b5c0-2e0bc7ebaa45.png)
Does it work for you all?

2022-01-26 10:17 UTC, dominic-heil requested changes
Re-tested everything on the kovan network. Worked fine for me. However, the `mintedNFTContracts` call is very unpractical as you need to enter and index manually. It would be a lot better if the call could return a whole array of contracts.

2022-01-26 10:23 UTC, JaPilgrim commented
> > While Testing and executing "Buy" I get just an error message "Fail" ![image](https://user-images.githubusercontent.com/92588281/151141759-8fd21209-e9d8-4285-b5c0-2e0bc7ebaa45.png) Does it work for you all?
> 
> @JaPilgrim Worked for me: https://kovan.etherscan.io/address/0x69779179BfF1429D89874882953B127e2e4C8eB2. Have you set a proper drop time and a large enough reservation timeout?

Yes I did set fitting droptime & timeout (also there was no error message, indicating the error doesnt result from not-reached time). 

However, when using the Deployed Version directly in Etherscan and not in Remix, "Buy" is working

2022-01-26 10:23 UTC, JaPilgrim approved these changes

2022-01-26 19:18 UTC, dominic-heil approved these changes
LGTM

2022-01-26 19:22 UTC, merged